#!/bin/sh
# update all forked fty repos and add commit message if not present
# 19.1.2017

REPOS=$1
BRANCH=$2
RPATH=~/42ity-github

if [ -z $BRANCH ]; then
    BRANCH = "master"
fi

if [ -z $REPOS ]; then
    REPOS=$(ls $RPATH | grep fty-)
fi


#for repo in $(ls $RPATH | grep fty-); do
for repo in $REPOS; do
    echo -e "\n"
    echo " --------- $repo ---------- "

    # add commit message to config
    COMM=`grep "commit" $RPATH/$repo/.git/config`
    if [ -z $COMM ]; then
        echo -e "[commit]\n\ttemplate = ~/.gitmessage\n" >> \
            $RPATH/$repo/.git/config
        echo -e "default commit message added\n"
    fi

    COLOR=`grep "color" $RPATH/$repo/.git/config`
    if [ -z $COLOR ]; then
        echo -e "[color]\n\tdiff = auto\n\tstatus = auto \n\tbranch = auto\n" \
            >> $RPATH/$repo/.git/config
        echo "Colors set."
    fi

    cd $RPATH/${repo}
    git checkout $BRANCH
    git pull upstream $BRANCH
done
